package:
  name: astec
  version: 0.0.1

source:
  path: ../../

build:
  number: 0

about:
  home: https://team.inria.fr/morpheme
  license: CECILL-C
  license_file: LICENSE
  summary: ASTEC package
  dev_url: https://github.com/astec-segmentation/astec
  doc_source_url: https://github.com/astec-segmentation/astec/blob/master/documentation/doc-astec.pdf

requirements:
  build:
    - setuptools
    - python >=2.7,<3
  host:
    - python >=2.7,<3
  run:
    - python >=2.7,<3
    - numpy
    - scipy